[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo-keccak256"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks.test]
cmd = "mojo -I . tests/test_keccak256.mojo"

[tasks.bench]
cmd = "python benchmarks/run_benchmarks.py"

[tasks."bench:json"]
cmd = "python benchmarks/run_benchmarks.py --json"

[dependencies]
mojo = ">=0.25.7.0.dev2025101905,<0.26"
python = ">=3.11,<3.13"
pycryptodome = "*"
eth-hash = "*"
pytest = "*"
